- name: install yum-utils
  yum: 
    name: yum-utils
    state: installed

- name: download docker repo
  shell: yum-config-manager  --add-repo  {{ docker_url }}
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install docker packages
  yum:
    name: "{{ docker_pack }}"
    state: installed
  notify: Start docker service
